In [1]:
from keras.models import load_model
from ast import literal_eval
import pandas as pd

from sentimentPredictor import SentimentPredictor
from TextAnalisys.wordToVecConverter import WordToVecConverterOneHotEncoder
from TextAnalisys.wordListToVecListConverter import WordListToVecListConverter
from TextAnalisys.docToVecConverter import DocToVecConverter
from TextAnalisys.textPreprocessor import TextPreprocessor

/home/algu/anaconda3/envs/keras/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
predictor = SentimentPredictor()
predictor.testMode = True

model = load_model("sentimentTesting/sentimentModel")
predictor.setModel(model)

frame = pd.DataFrame.from_csv("databasePositiveNegativeSeparatedWords.csv")
wordLists = frame["text"].apply(literal_eval).values
wordToVecConverter = WordToVecConverterOneHotEncoder()
wordToVecConverter.fit(wordLists)

wordListToVecListConverter = WordListToVecListConverter()
wordListToVecListConverter.setWordToVecConverter(wordToVecConverter)
docToVecConverter = DocToVecConverter()
docToVecConverter.setWordListToVecListConverter(wordListToVecListConverter)
textPreprocessor = TextPreprocessor(addPartOfSpeechTagToWords=True)
docToVecConverter.setTextPreprocessor(textPreprocessor)

predictor.setDocToVecConverter(docToVecConverter)

/home/algu/anaconda3/envs/keras/lib/python3.5/site-packages/ipykernel_launcher.py:7: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  import sys


In [3]:
predictor.predict("Пойду повешусь")

[ 343 4875]
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0  343 4875]]


-0.9393972

In [4]:
predictor.predict("какой кашерный день")

[354   0 134]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0 354   0 134]]


0.12098545

In [5]:
predictor.predict("дом милый дом")

[485 227 485]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0 485 227 485]]


-0.95290935

In [6]:
predictor.predict("подайте на пропитание")

[ 8183 24367]
[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0  8183 24367]]


-0.85441244

In [7]:
predictor.predict("северная корея начала разводить собак")

[ 1716 17585     0 22344   603]
[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0  1716
  17585     0 22344   603]]


-0.99365616

In [8]:
predictor.predict("плохая новость")

[533 826]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0 533 826]]


-0.9594495

In [3]:
predictor.predict("хорошая новость")

[133 826]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0 133 826]]


0.62822175

In [10]:
predictor.predict("фильм мне понравился")

[ 179 1424]
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0  179 1424]]


-0.10420162

In [11]:
predictor.predict("фильм был ужасен")

[ 179   44 3176]
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0  179   44 3176]]


-0.84855044

In [4]:
predictor.predict("солнце светит птички поют")

[ 441 4593 8140 5479]
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0  441 4593 8140 5479]]


-0.9892106